Repository FusionPulseTech/FusionPulseTech-portfolio, pull requests merged in 2024-08, with the labels that each got.

#16 docs(services-menu): Update services-menu done
  ftp-portfolio/.gitignore
  ftp-portfolio/src/components/Services.tsx
Labels: documentation

#18 feat(team-member):Update team member data done
  ftp-portfolio/src/components/Team.tsx
Labels: Feature

#20 fix(social-link): Add Github and LinkedIn done
  ftp-portfolio/next.config.mjs
  ftp-portfolio/public/employee.jpg
  ftp-portfolio/src/components/Footer.tsx
  ftp-portfolio/src/components/Hero.tsx
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement

#24 fix(contact-us): Email integration in contact us done
  ftp-portfolio/package-lock.json
  ftp-portfolio/package.json
  ftp-portfolio/src/app/layout.tsx
  ftp-portfolio/src/components/Blog.tsx
  ftp-portfolio/src/components/Contact.tsx
  ftp-portfolio/src/components/Footer.tsx
  ftp-portfolio/src/components/Hero.tsx
  ftp-portfolio/src/components/Project.tsx
  ftp-portfolio/src/components/Services.tsx
  ftp-portfolio/src/components/Skills.tsx
  ftp-portfolio/src/components/Stats.tsx
Labels: enhancement

#25 Deplyment configuration
  ftp-portfolio/app.js
  ftp-portfolio/next.config.js
  ftp-portfolio/package.json
Labels: enhancement

#27 fix(social-link):Add FB Done
  ftp-portfolio/src/app/layout.tsx
  ftp-portfolio/src/components/Blog.tsx
  ftp-portfolio/src/components/Footer.tsx
  ftp-portfolio/src/components/Header.tsx
  ftp-portfolio/src/components/Hero.tsx
Labels: enhancement

#29 fix(update-logo):Update logo Done
  ftp-portfolio/public/Logo.png
  ftp-portfolio/public/meeting.jpg
  ftp-portfolio/public/meeting2.jpg
  ftp-portfolio/src/components/Footer.tsx
  ftp-portfolio/src/components/Header.tsx
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement

#31 fix(team-mates): Update team list done.
  ftp-portfolio/next.config.js
  ftp-portfolio/src/components/About.tsx
  ftp-portfolio/src/components/Hero.tsx
  ftp-portfolio/src/components/Services.tsx
  ftp-portfolio/src/components/Skills.tsx
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement

#33 fix(team-mates): Update team pattern done.
  ftp-portfolio/next.config.js
  ftp-portfolio/src/components/Project.tsx
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement

#38 docs(blog): Custom Software Development Done
  ftp-portfolio/blog/Website Development and Custom Software Development.docx
Labels: documentation

#41 fix(service): Correction Button allignment done.
  ftp-portfolio/public/development.png
  ftp-portfolio/public/strategy-development.png
  ftp-portfolio/src/components/Blog.tsx
  ftp-portfolio/src/components/Hero.tsx
  ftp-portfolio/src/components/Project.tsx
  ftp-portfolio/src/components/Services.tsx
  ftp-portfolio/src/components/Skills.tsx
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement

#43 fix(service): Correction Card Description done.
  ftp-portfolio/src/components/Blog.tsx
  ftp-portfolio/src/components/Hero.tsx
  ftp-portfolio/src/components/Project.tsx
  ftp-portfolio/src/components/Services.tsx
  ftp-portfolio/src/components/Skills.tsx
  ftp-portfolio/src/components/Stats.tsx
Labels: enhancement

#45 fix(team): Correction Linkedin link done.
  ftp-portfolio/src/components/Team.tsx
Labels: enhancement
